export const products = [
    {
      id: 1,
      name: "Cà phê sữa tươi",
      price: 32000,
      description: "A shot of espresso with hot water",
      image: "/static/images/products/milk_coffee_&_bacxiu.jpg",
      isSoldOut: false,
      sizes: [],
      sl: 1,
    },
    {
      id: 2,
      name: "Cà phê đá",
      price: 23000,
      description: "A shot of espresso with hot water",
      image: "/static/images/products/coffee_da.jpg",
      isSoldOut: false,
      sizes: [],
      sl: 1,
    },
    {
      id: 3,
      name: "Cà phê sữa đá",
      price: 27000,
      description: "A shot of espresso with hot water",
      image: "/static/images/products/coffee.jpg",
      isSoldOut: false,
      sizes: [],
      sl: 1,
    },
    {
      id: 4,
      name: "Bạc xỉu",
      price: 30000,
      description: "A shot of espresso with hot water",
      image: "/static/images/products/milk_coffee_&_bacxiu.jpg",
      isSoldOut: false,
      sizes: [],
      sl: 1,
    },
    {
      id: 5,
      name: "Capuchino - Latte",
      price: 37000,
      description: "A shot of espresso with hot water",
      image: "/static/images/products/capuchino_latte.jpg",
      isSoldOut: true,
      sizes: [],
      sl: 1,
    },
    {
      id: 6,
      name: "Americano",
      price: 30000,
      description: "A shot of espresso with hot water",
      image: "/static/images/products/coffee_da.jpg",
      isSoldOut: false,
      sizes: [],
      sl: 1,
    },
    {
      id: 7,
      name: "Cafe muối",
      price: 32000,
      description: "A shot of espresso with hot water",
      image: "/static/images/products/cafe_muoi.jpg",
      isSoldOut: false,
      sizes: [
        {
          label: "M",
          price: 32000,
        },
        {
          label: "L",
          price: 38000,
        },
      ],
      sl: 1,
    },
    {
      id: 8,
      name: "Cacao muối",
      price: 30000,
      description: "A shot of espresso with hot water",
      image: "/static/images/products/cacao_muoi.jpg",
      isSoldOut: false,
      sizes: [
        {
          label: "M",
          price: 30000,
        },
        {
          label: "L",
          price: 36000,
        },
      ],
      sl: 1,
    },
  ];